theme = "custom_transparent"

[editor]
true-color = true
bufferline = "multiple"
color-modes = true
shell = ["elvish", "-c"]
line-number = "relative"
cursorline = true
cursorcolumn = true
completion-replace = true
popup-border = "all"
end-of-line-diagnostics = "hint"

[editor.statusline]
right = [
  "diagnostics",
  "selections",
  "register",
  "position",
  "file-encoding",
  "spacer",
  "version-control"
]

[editor.lsp]
display-inlay-hints = true
# inlay-hints-length-limit = 40

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[editor.inline-diagnostics]
cursor-line = "hint"
# other-lines = "error"
