theme = "custom_transparent"

[editor]
true-color = true
bufferline = "multiple"
color-modes = true
shell = ["elvish", "-c"]
line-number = "relative"
cursorline = true
cursorcolumn = true
# popup-border = "all"

[editor.statusline]
right = [
  "diagnostics",
  "selections",
  "register",
  "position",
  "file-encoding",
  "spacer",
  "version-control"
]

[editor.lsp]
display-inlay-hints = true
# inlay-hints-length-limit = 40
